/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import sim.tp1.CongruencialLineal;
import sim.tp1.CongruencialMultiplicativo;
import sim.tp1.TestChiCuadrado;

/**
 *
 * @author nicolastomassi
 */
public class vtnChiCuadrado extends javax.swing.JDialog {
    
    private vtnDatosChiCuadrado vtnDatos;
    private TestChiCuadrado tcc;
    /**
     * Creates new form vtnChiCuadrado
     */
    public vtnChiCuadrado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.lblAceptado.setVisible(false);
        this.lblCancelado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaChi = new javax.swing.JTable();
        cmbForma = new javax.swing.JComboBox<>();
        btnGraficar = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        lblChiCalculado = new javax.swing.JLabel();
        lblCancelado = new javax.swing.JLabel();
        lblAceptado = new javax.swing.JLabel();
        lblExplicacion = new javax.swing.JLabel();
        lblChiTabulado = new javax.swing.JLabel();
        btnTest1 = new javax.swing.JButton();
        lblGrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Intervalo", "fo", "fe", "(fo - fe)^2", "((fo - fe)^2)/fe"
            }
        ));
        tablaChi.setName(""); // NOI18N
        jScrollPane1.setViewportView(tablaChi);

        cmbForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(seleccione una opción)", "Generar números aleatorios por Java", "Generar números aleatorios por método Lineal ( Mixto)" }));
        cmbForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormaActionPerformed(evt);
            }
        });

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnTest.setText("Ejecutar Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        lblChiCalculado.setText("X^2 :");
        lblChiCalculado.setToolTipText("");

        lblCancelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/error.png"))); // NOI18N

        lblAceptado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapas-y-banderas.png"))); // NOI18N

        lblChiTabulado.setText("X^2(tabulado) :");
        lblChiTabulado.setToolTipText("");

        btnTest1.setText("Visualizar serie generada");
        btnTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest1ActionPerformed(evt);
            }
        });

        lblGrado.setText("Grado de Libertad:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCancelado)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChiTabulado)
                            .addComponent(lblChiCalculado)
                            .addComponent(lblGrado))
                        .addGap(155, 155, 155))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblExplicacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTest1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbForma, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(lblAceptado)
                    .addContainerGap(439, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cmbForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChiCalculado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChiTabulado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrado)
                .addGap(20, 20, 20)
                .addComponent(lblCancelado)
                .addGap(26, 26, 26)
                .addComponent(lblExplicacion)
                .addGap(60, 60, 60))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(393, Short.MAX_VALUE)
                    .addComponent(lblAceptado)
                    .addGap(101, 101, 101)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarTabla()
    {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaChi.getModel();
        int aux = modelo.getRowCount();
        for ( int i = 0; i < aux ; i++)
        {
            modelo.removeRow(0);
        }
        
    }
    private void cmbFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormaActionPerformed
        this.limpiarTabla();
        this.lblAceptado.setVisible(false);
        this.lblCancelado.setVisible(false);
        this.lblExplicacion.setVisible(false);
        this.lblGrado.setText("Grados de Libertad: ");
        this.lblChiCalculado.setText("X^2: ");
        this.lblChiTabulado.setText("X^2(tabulado):");
        int opc = cmbForma.getSelectedIndex();
        
        if (opc == 1)
        {
            this.vtnDatos = new vtnDatosChiCuadrado(new javax.swing.JFrame(), true);
            vtnDatos.setVisible(true);
        }
    }//GEN-LAST:event_cmbFormaActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        
        for (int i = 0; i < this.tablaChi.getRowCount(); i++)
        {
            dtsc.addValue(Integer.parseInt((this.tablaChi.getValueAt(i, 1).toString())), "Observada", this.tablaChi.getValueAt(i, 0).toString());
            dtsc.addValue(Double.parseDouble((this.tablaChi.getValueAt(i, 2).toString())), "Esperada", this.tablaChi.getValueAt(i, 0).toString());
        }
        
        JFreeChart jf = ChartFactory.createBarChart3D("Grafica de frecuencias", "Intervalos", "Frecuencia", dtsc, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel c = new ChartPanel(jf);
        JDialog vtn = new JDialog(new javax.swing.JFrame(), true);
        vtn.add(c);
        vtn.setSize(900, 700);
        vtn.setLocationRelativeTo(null);
        vtn.setVisible(true);
        
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        
        
        if (cmbForma.getSelectedIndex() == 1)
        {
            tcc = new TestChiCuadrado( this.vtnDatos.getNumIntervalos(), this.vtnDatos.getNumAGenerar());
        }
        else 
        {
            //ValoresMetCongMult vtnDatos = new ValoresMetCongMult(new javax.swing.JFrame(), true);
            ValoresMetCongLineal vtnDatos = new ValoresMetCongLineal(new javax.swing.JFrame(), true);
            vtnDatos.setVisible(true);
            CongruencialLineal mcm = vtnDatos.datos();
            vtnDatosChiCuadrado vtnDatos2 = new vtnDatosChiCuadrado(new javax.swing.JFrame(), true);
            vtnDatos2.setVisible(true);
            for (int i = 0; i < vtnDatos2.getNumAGenerar(); i++)
            {
                mcm.generarNumero();
            }
            ArrayList<Double> datos = mcm.numerosGenerados();
            tcc = new TestChiCuadrado(vtnDatos2.getNumIntervalos(), datos);
        }
        ArrayList<String> intervalos = tcc.listaIntervalos();
        ArrayList<Double> resta = tcc.diferenciaYalCuadrado();
        ArrayList<Double> division = tcc.generarSumatoriaChi();
        double esperada = tcc.getEsperada();
        int observado[] = tcc.getIntervalos();
            
        for( int i = 0; i < intervalos.size() ; i++)
        {
            this.agregarFilas(intervalos.get(i), String.valueOf(observado[i]), String.valueOf(esperada), String.valueOf(resta.get(i)), String.valueOf(division.get(i)));
        }
        this.lblChiCalculado.setText(this.lblChiCalculado.getText() + tcc.generarChiCuadradoCalculado());
        this.lblChiTabulado.setText(this.lblChiTabulado.getText() + tcc.generarChiCuadradoTabulado());
        this.lblGrado.setText(this.lblGrado.getText() + String.valueOf(this.tcc.getGradosDeLibertad()));
        if (tcc.esAprobado()) 
        {
            this.lblAceptado.setVisible(true);
            this.lblExplicacion.setText("Los numeros pseudo-aleatorios generados satisfacen el test de prueba");
            this.lblExplicacion.setVisible(true);
        }
        else
        {
            this.lblCancelado.setVisible(true);
            this.lblExplicacion.setText("Los numeros pseudo-aleatorios generados NO satisfacen el test de prueba");
            this.lblExplicacion.setVisible(true);
        }
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest1ActionPerformed
        vtnSerieGenerada vtn = new vtnSerieGenerada(new javax.swing.JFrame(), true);
        vtn.setA1(this.tcc.getNumerosAleatorios());
        vtn.cargarTabla();
        vtn.setVisible(true);
    }//GEN-LAST:event_btnTest1ActionPerformed

    private void agregarFilas(String intervalo, String observado, String esperado, String resta, String dividido)
    {
        DefaultTableModel model =  (DefaultTableModel) this.tablaChi.getModel();
        String datos[] = {intervalo, observado, esperado, resta, dividido};
        model.addRow(datos);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vtnChiCuadrado dialog = new vtnChiCuadrado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnTest1;
    private javax.swing.JComboBox<String> cmbForma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAceptado;
    private javax.swing.JLabel lblCancelado;
    private javax.swing.JLabel lblChiCalculado;
    private javax.swing.JLabel lblChiTabulado;
    private javax.swing.JLabel lblExplicacion;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JTable tablaChi;
    // End of variables declaration//GEN-END:variables
}
